//! B1-SCHEMA-1 contract validation. Normative: SPEC/25-b1-schema-1.md.
//!
//! Validates a document against a schema generated by `contracts/src/schema.ts`. The keyword set is
//! closed — that builder is the only thing that emits these schemas — so this handles eleven
//! keywords and one pattern shape rather than JSON Schema in general.
//!
//! Two behaviours invert what a general validator would do, and both are the point:
//!
//!   * An unrecognized keyword is an **error**. Standard JSON Schema ignores unknown keywords,
//!     which here would mean enforcement silently weakening the day the builder learns a new one —
//!     the validator would keep reporting valid while not checking the new constraint.
//!   * An unsupported pattern shape is an **error**, not a skip. Passing over a constraint it
//!     cannot evaluate would make the validator report a result it never established.

use crate::canon::Json;
use std::collections::BTreeMap;
use std::fmt;

/// Keywords the validator acts on, plus the annotations it knowingly ignores. Anything else is a
/// schema defect (SPEC/25 §3).
const VALIDATING: [&str; 11] = [
    "type", "properties", "required", "additionalProperties", "anyOf", "items", "minimum",
    "maximum", "enum", "const", "pattern",
];
const ANNOTATIONS: [&str; 5] = ["$schema", "$id", "title", "description", "x-b1-unit"];

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Violation {
    MissingRequired { path: String, field: String },
    TypeMismatch { path: String, expected: String, actual: String },
    AdditionalProperty { path: String, field: String },
    Enum { path: String, value: String },
    Const { path: String, expected: String, actual: String },
    Range { path: String, value: i64, detail: String },
    Pattern { path: String, value: String, pattern: String },
    /// No permitted form matched. Carries why each branch failed: for a nullable object, knowing
    /// only that "no form matched" leaves the caller unable to tell a wrong type from one bad
    /// sub-field, which is the difference between a five-second fix and a hunt.
    AnyOf { path: String, branch_failures: Vec<String> },
    /// A defect in the schema, not the document.
    UnknownKeyword { path: String, keyword: String },
    /// A defect in the schema, not the document.
    UnsupportedPattern { path: String, pattern: String },
}

impl Violation {
    pub fn token(&self) -> &'static str {
        match self {
            Violation::MissingRequired { .. } => "B1_SCHEMA_MISSING_REQUIRED",
            Violation::TypeMismatch { .. } => "B1_SCHEMA_TYPE_MISMATCH",
            Violation::AdditionalProperty { .. } => "B1_SCHEMA_ADDITIONAL_PROPERTY",
            Violation::Enum { .. } => "B1_SCHEMA_ENUM",
            Violation::Const { .. } => "B1_SCHEMA_CONST",
            Violation::Range { .. } => "B1_SCHEMA_RANGE",
            Violation::Pattern { .. } => "B1_SCHEMA_PATTERN",
            Violation::AnyOf { .. } => "B1_SCHEMA_ANY_OF",
            Violation::UnknownKeyword { .. } => "B1_SCHEMA_UNKNOWN_KEYWORD",
            Violation::UnsupportedPattern { .. } => "B1_SCHEMA_UNSUPPORTED_PATTERN",
        }
    }

    /// True where the fault lies in the schema rather than the document being checked.
    pub fn is_schema_defect(&self) -> bool {
        matches!(
            self,
            Violation::UnknownKeyword { .. } | Violation::UnsupportedPattern { .. }
        )
    }

    pub fn path(&self) -> &str {
        match self {
            Violation::MissingRequired { path, .. }
            | Violation::TypeMismatch { path, .. }
            | Violation::AdditionalProperty { path, .. }
            | Violation::Enum { path, .. }
            | Violation::Const { path, .. }
            | Violation::Range { path, .. }
            | Violation::Pattern { path, .. }
            | Violation::AnyOf { path, .. }
            | Violation::UnknownKeyword { path, .. }
            | Violation::UnsupportedPattern { path, .. } => path,
        }
    }
}

impl fmt::Display for Violation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let at = |p: &str| if p.is_empty() { "/".to_string() } else { p.to_string() };
        match self {
            Violation::MissingRequired { path, field } => {
                write!(f, "{}: required field `{field}` is absent", at(path))
            }
            Violation::TypeMismatch { path, expected, actual } => {
                write!(f, "{}: expected {expected}, found {actual}", at(path))
            }
            Violation::AdditionalProperty { path, field } => write!(
                f,
                "{}: `{field}` is not declared by the schema",
                at(path)
            ),
            Violation::Enum { path, value } => {
                write!(f, "{}: {value:?} is not a permitted value", at(path))
            }
            Violation::Const { path, expected, actual } => {
                write!(f, "{}: expected {expected:?}, found {actual:?}", at(path))
            }
            Violation::Range { path, value, detail } => {
                write!(f, "{}: {value} is {detail}", at(path))
            }
            Violation::Pattern { path, value, pattern } => write!(
                f,
                "{}: {value:?} does not match {pattern}",
                at(path)
            ),
            Violation::AnyOf { path, branch_failures } => {
                write!(f, "{}: no permitted form matched", at(path))?;
                for (i, why) in branch_failures.iter().enumerate() {
                    write!(f, "\n      form {}: {why}", i + 1)?;
                }
                Ok(())
            }
            Violation::UnknownKeyword { path, keyword } => write!(
                f,
                "schema defect at {}: keyword `{keyword}` is outside B1-SCHEMA-1; \
                 refusing rather than ignoring it, because ignoring would keep reporting valid \
                 while not checking the constraint",
                at(path)
            ),
            Violation::UnsupportedPattern { path, pattern } => write!(
                f,
                "schema defect at {}: pattern {pattern:?} is outside the supported shape; \
                 refusing rather than skipping it, because skipping would report a result never \
                 established",
                at(path)
            ),
        }
    }
}

// --- the supported pattern shape ---------------------------------------------

/// `^<literal>?<char-class>{n}$` or `^<literal>?<char-class>{n,m}$`, per SPEC/25 §4.
#[derive(Debug)]
struct AnchoredPattern {
    literal: String,
    ranges: Vec<(char, char)>,
    min: usize,
    max: usize,
}

impl AnchoredPattern {
    fn parse(pattern: &str) -> Option<AnchoredPattern> {
        let body = pattern.strip_prefix('^')?.strip_suffix('$')?;

        let class_start = body.find('[')?;
        let literal = body[..class_start].to_string();
        // A literal prefix must be literal: anything that could be a metacharacter is out of shape.
        if literal.chars().any(|c| !c.is_ascii_alphanumeric() && c != ':' && c != '_' && c != '-') {
            return None;
        }

        let rest = &body[class_start + 1..];
        let class_end = rest.find(']')?;
        let class = &rest[..class_end];
        let quantifier = &rest[class_end + 1..];

        let mut ranges = Vec::new();
        let chars: Vec<char> = class.chars().collect();
        let mut i = 0;
        while i < chars.len() {
            if i + 2 < chars.len() && chars[i + 1] == '-' {
                ranges.push((chars[i], chars[i + 2]));
                i += 3;
            } else {
                // A trailing `-` is a literal hyphen, which is how [a-z0-9_-] ends.
                ranges.push((chars[i], chars[i]));
                i += 1;
            }
        }
        if ranges.is_empty() {
            return None;
        }

        let inner = quantifier.strip_prefix('{')?.strip_suffix('}')?;
        let (min, max) = match inner.split_once(',') {
            Some((lo, hi)) => (lo.parse().ok()?, hi.parse().ok()?),
            None => {
                let n: usize = inner.parse().ok()?;
                (n, n)
            }
        };

        Some(AnchoredPattern { literal, ranges, min, max })
    }

    fn matches(&self, value: &str) -> bool {
        let Some(rest) = value.strip_prefix(&self.literal) else {
            return false;
        };
        let count = rest.chars().count();
        if count < self.min || count > self.max {
            return false;
        }
        rest.chars()
            .all(|c| self.ranges.iter().any(|(lo, hi)| c >= *lo && c <= *hi))
    }
}

// --- validation ----------------------------------------------------------------

fn type_name(v: &Json) -> &'static str {
    match v {
        Json::Null => "null",
        Json::Bool(_) => "boolean",
        Json::Int(_) => "integer",
        Json::Str(_) => "string",
        Json::Arr(_) => "array",
        Json::Obj(_) => "object",
    }
}

fn schema_members(schema: &Json) -> Option<&BTreeMap<String, Json>> {
    match schema {
        Json::Obj(m) => Some(m),
        _ => None,
    }
}

fn str_list(node: Option<&Json>) -> Vec<String> {
    match node {
        Some(Json::Arr(items)) => items
            .iter()
            .filter_map(|i| i.as_str().map(String::from))
            .collect(),
        _ => Vec::new(),
    }
}

/// Validates `value` against `schema`, returning **every** violation found.
///
/// All violations rather than the first: three missing fields and thirty are different situations,
/// and reporting them identically discards the signal that tells them apart (SPEC/25 §5).
pub fn validate(value: &Json, schema: &Json) -> Vec<Violation> {
    // Schema defects are found by scanning the whole schema, before and independently of the
    // document.
    //
    // Detecting them only while walking the document would make enforcement depend on what the
    // document happens to contain: an unknown keyword on an optional field nothing populates would
    // never be reached, and the validator would keep reporting valid over a constraint it never
    // checked — exactly the silent weakening §3 exists to prevent. A defect in the contract is a
    // property of the contract.
    let mut out = scan_schema(schema, "");
    validate_at(value, schema, "", &mut out);
    out
}

/// Walks the entire schema looking for constructs this validator cannot enforce.
fn scan_schema(schema: &Json, path: &str) -> Vec<Violation> {
    let mut out = Vec::new();
    let Some(members) = schema_members(schema) else {
        return out;
    };

    for key in members.keys() {
        if !VALIDATING.contains(&key.as_str()) && !ANNOTATIONS.contains(&key.as_str()) {
            out.push(Violation::UnknownKeyword {
                path: path.to_string(),
                keyword: key.clone(),
            });
        }
    }

    if let Some(Json::Str(pattern)) = members.get("pattern") {
        if AnchoredPattern::parse(pattern).is_none() {
            out.push(Violation::UnsupportedPattern {
                path: path.to_string(),
                pattern: pattern.clone(),
            });
        }
    }

    if let Some(props) = members.get("properties").and_then(schema_members) {
        for (field, sub) in props {
            out.extend(scan_schema(sub, &format!("{path}/{field}")));
        }
    }
    if let Some(items) = members.get("items") {
        out.extend(scan_schema(items, &format!("{path}/[]")));
    }
    if let Some(Json::Arr(branches)) = members.get("anyOf") {
        for (i, branch) in branches.iter().enumerate() {
            out.extend(scan_schema(branch, &format!("{path}/anyOf/{i}")));
        }
    }

    out
}

fn validate_at(value: &Json, schema: &Json, path: &str, out: &mut Vec<Violation>) {
    let Some(members) = schema_members(schema) else {
        return;
    };

    if let Some(Json::Arr(branches)) = members.get("anyOf") {
        // A branch matches if it produces no *document* violations. A schema defect inside a branch
        // is surfaced regardless — it is not something a sibling branch can excuse.
        let mut matched = false;
        let mut branch_failures = Vec::new();
        for branch in branches {
            let mut branch_violations = Vec::new();
            validate_at(value, branch, path, &mut branch_violations);
            for v in branch_violations.iter().filter(|v| v.is_schema_defect()) {
                out.push(v.clone());
            }
            let document_failures: Vec<&Violation> = branch_violations
                .iter()
                .filter(|v| !v.is_schema_defect())
                .collect();
            if document_failures.is_empty() {
                matched = true;
            } else {
                branch_failures.push(
                    document_failures
                        .iter()
                        .map(|v| v.to_string())
                        .collect::<Vec<_>>()
                        .join("; "),
                );
            }
        }
        if !matched {
            out.push(Violation::AnyOf {
                path: path.to_string(),
                branch_failures,
            });
        }
        return;
    }

    if let Some(Json::Str(expected)) = members.get("type") {
        let actual = type_name(value);
        let ok = match expected.as_str() {
            "object" => matches!(value, Json::Obj(_)),
            "array" => matches!(value, Json::Arr(_)),
            "string" => matches!(value, Json::Str(_)),
            "integer" => matches!(value, Json::Int(_)),
            "boolean" => matches!(value, Json::Bool(_)),
            "null" => matches!(value, Json::Null),
            _ => true,
        };
        if !ok {
            out.push(Violation::TypeMismatch {
                path: path.to_string(),
                expected: expected.clone(),
                actual: actual.to_string(),
            });
            return; // further checks against the wrong type would only produce noise
        }
    }

    if let Some(Json::Str(expected)) = members.get("const") {
        if let Json::Str(actual) = value {
            if actual != expected {
                out.push(Violation::Const {
                    path: path.to_string(),
                    expected: expected.clone(),
                    actual: actual.clone(),
                });
            }
        }
    }

    if let Json::Str(actual) = value {
        let permitted = str_list(members.get("enum"));
        if !permitted.is_empty() && !permitted.contains(actual) {
            out.push(Violation::Enum {
                path: path.to_string(),
                value: actual.clone(),
            });
        }

        if let Some(Json::Str(pattern)) = members.get("pattern") {
            match AnchoredPattern::parse(pattern) {
                Some(p) => {
                    if !p.matches(actual) {
                        out.push(Violation::Pattern {
                            path: path.to_string(),
                            value: actual.clone(),
                            pattern: pattern.clone(),
                        });
                    }
                }
                // An unsupported pattern is already reported by scan_schema; not repeated here.
                None => {}
            }
        }
    }

    if let Json::Int(n) = value {
        if let Some(Json::Int(min)) = members.get("minimum") {
            if n < min {
                out.push(Violation::Range {
                    path: path.to_string(),
                    value: *n,
                    detail: format!("below the minimum of {min}"),
                });
            }
        }
        if let Some(Json::Int(max)) = members.get("maximum") {
            if n > max {
                out.push(Violation::Range {
                    path: path.to_string(),
                    value: *n,
                    detail: format!("above the maximum of {max}"),
                });
            }
        }
    }

    if let Json::Arr(items) = value {
        if let Some(item_schema) = members.get("items") {
            for (i, item) in items.iter().enumerate() {
                validate_at(item, item_schema, &format!("{path}/{i}"), out);
            }
        }
    }

    if let Json::Obj(doc) = value {
        // `required` means present. A required-and-nullable field must appear carrying null;
        // omitting it is a violation, because "not recorded" and "recorded as nothing" are
        // different claims (SPEC/25 §2).
        for field in str_list(members.get("required")) {
            if !doc.contains_key(&field) {
                out.push(Violation::MissingRequired {
                    path: path.to_string(),
                    field,
                });
            }
        }

        let properties = members.get("properties").and_then(schema_members);

        if matches!(members.get("additionalProperties"), Some(Json::Bool(false))) {
            for field in doc.keys() {
                let declared = properties.map(|p| p.contains_key(field)).unwrap_or(false);
                if !declared {
                    out.push(Violation::AdditionalProperty {
                        path: path.to_string(),
                        field: field.clone(),
                    });
                }
            }
        }

        if let Some(props) = properties {
            for (field, sub_schema) in props {
                if let Some(sub_value) = doc.get(field) {
                    validate_at(sub_value, sub_schema, &format!("{path}/{field}"), out);
                }
            }
        }
    }
}

/// Loads a generated schema from disk.
pub fn load(path: &str) -> Result<Json, String> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| format!("cannot read schema {path}: {e}"))?;
    crate::canon::parse(&text).map_err(|e| format!("schema {path} is not valid JSON: {}", e.token()))
}

/// Locates `contracts/generated/<name>` by walking up from the current directory.
///
/// The schema is read at runtime rather than compiled in, so the contract keeps exactly one
/// definition — authored in TypeScript, enforced here, with no generated Rust to drift.
pub fn find_generated(name: &str) -> Option<String> {
    if let Ok(root) = std::env::var("B1_ROOT") {
        let candidate = format!("{root}/contracts/generated/{name}");
        if std::path::Path::new(&candidate).exists() {
            return Some(candidate);
        }
    }

    let mut dir = std::env::current_dir().ok()?;
    loop {
        let candidate = dir.join("contracts").join("generated").join(name);
        if candidate.exists() {
            return Some(candidate.to_string_lossy().into_owned());
        }
        if !dir.pop() {
            return None;
        }
    }
}
